services:

  backend:
    build: ./backend
    container_name: flashsale_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/flashsale
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  worker:
    build: ./backend
    container_name: flashsale_worker
    command: python -m app.workers.payment_worker
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/flashsale
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    container_name: flashsale_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API: http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: flashsale_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flashsale
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d flashsale"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: flashsale_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flashsale_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    container_name: flashsale_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: flashsale_grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data: