global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "flash-sale-api"
    static_configs:
      - targets: ["backend:8000"] 

  - job_name: "worker"
    static_configs:
      - targets: ["backend:8000"] 